### ISSUE TITLE
Inaccessible host

### ISSUE THREAD

**Issue by jbies121** [peterkimzz/aws-ssm-send-command#12]
**Describe the bug**
Trying to run this action with correct IAM roles applied, and seeing this error (region code redacted):
```message: "Inaccessible host: `ssm.us-west-**.amazonaws.com'. This service may not be available in the `us-west-**' region."```

SSM is available in this region.

**To Reproduce**
Passing the aws region as a repository secret was giving me the same error but with ssm.***.amazonaws.com.
I set the region in the action and still saw this error.

**Expected behavior**
This action should be able to locate the AWS resource

**Full Error**
```
Run peterkimzz/aws-ssm-send-command@master
/home/runner/work/_actions/peterkimzz/aws-ssm-send-command/master/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

UnknownEndpoint: Inaccessible host: `ssm.us-west-**.amazonaws.com'. This service may not be available in the `us-west-**' region.
    at Request.ENOTFOUND_ERROR (/home/runner/work/_actions/peterkimzz/aws-ssm-send-command/master/node_modules/aws-sdk/lib/event_listeners.js:507:46)
    at Request.callListeners (/home/runner/work/_actions/peterkimzz/aws-ssm-send-command/master/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/runner/work/_actions/peterkimzz/aws-ssm-send-command/master/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/runner/work/_actions/peterkimzz/aws-ssm-send-command/master/node_modules/aws-sdk/lib/request.js:688:14)
    at ClientRequest.error (/home/runner/work/_actions/peterkimzz/aws-ssm-send-command/master/node_modules/aws-sdk/lib/event_listeners.js:339:22)
    at ClientRequest.<anonymous> (/home/runner/work/_actions/peterkimzz/aws-ssm-send-command/master/node_modules/aws-sdk/lib/http/node.js:96:19)
    at ClientRequest.emit (events.js:210:5)
    at ClientRequest.EventEmitter.emit (domain.js:475:20)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5) {
  message: "Inaccessible host: `ssm.us-west-**.amazonaws.com'. This service may not be available in the `us-west-**' region.",
  code: 'UnknownEndpoint',
  region: 'us-west-**',
  hostname: 'ssm.us-west-**.amazonaws.com',
  retryable: true,
  originalError: Error: getaddrinfo ENOTFOUND ssm.us-west-**.amazonaws.com```

**Comment by jbies121** [comment]
issue seems to be with the aws-sdk, I'll close this out and raise with them. Cheers!

**Comment by ljunokas** [comment]
were you able to resolve it?

**Comment by jarretmoses** [comment]
I am too having this issue. @jbies121 did you get an update?

**Comment by devupmaster** [comment]
UnknownEndpoint: Inaccessible host: `ssm.***.amazonaws.com'. This service may not be available in the `***' region.

![image](https://user-images.githubusercontent.com/92178071/192776733-865b9560-5b0d-4904-bf66-5d8c7b8f9faf.png)

**Comment by devupmaster** [comment]
endpoints have been modified?
